### ISSUE TITLE
Documentation of the algebra interface

### ISSUE THREAD

**Issue by alvinary** [coli-saar/alto#64]
Section 7 of the wiki lists the algebras implemented in Alto, but the apidoc links are broken.
Are there any sample definitions which could be used as examples for defining new algebras, or is there any additional material which could serve as reference?

I hope this request does not inconvenience you!

**Comment by alexanderkoller** [comment]
Hi, thank you for submitting the issue and pointing out this documentation bug! I have fixed the wiki page. Let me know if this clears things up for you, or whether we can be of further assistance.

**Comment by alvinary** [comment]
This clears things up, thanks! I will submit another issue if I run into some other problem, hope that helps!
