### ISSUE TITLE
Negative weights

### ISSUE THREAD

**Issue by akoehn** [coli-saar/alto#67]
IRTGs currently cannot contain negative weights when constructing with an IrtgInputCodec. It expects:
```
NUMBER : [0-9.] ([0-9.eE-]*);
...
weight     : '[' NUMBER ']';
```
I guess nobody ever wanted negative weights and therefore just did not think about negative weights.  Is there another reason for only accepting positive weights or can I extend it for negative ones?

**Comment by alexanderkoller** [comment]
No, go ahead and add the optional minus.

**Comment by akoehn** [comment]
Added in 38cd3740cac7263066f2d95084f349c097372c6d.
