### ISSUE TITLE
merge TreeAutomaton.g4 and irtg.g4

### ISSUE THREAD

**Issue by akoehn** [coli-saar/alto#68]
The Antlr grammar for tree automata is a subset of the irtg grammar.  Only the single line `fta: auto_rule+;` is in `treeautomaton.g4` but not in `irtg.g4`.

I propose we merge those two file.  I tried that already, it works as expected and removes code duplication (which I noticed when I had to redefine the meaning of `NUMBER` for #67 twice).

**Comment by alexanderkoller** [comment]
If this can be done, great!
