### ISSUE TITLE
The alto-examples.zip link is broken

### ISSUE THREAD

**Issue by vsotofrances** [coli-saar/alto#74]
The link alto-examples.zip goes to bitbucket but it does not work.

Regards
Victor

**Comment by alexanderkoller** [comment]
Hi,

where is this link? I'd be happy to fix it.

In the meantime, you can find all examples here: https://github.com/coli-saar/alto/tree/master/examples

Best,
Alexander.

**Comment by vmsf** [comment]
https://bitbucket.org/tclup/alto/downloads/alto-examples.zip

(the link is referenced at the github page...
https://github.com/coli-saar/alto/wiki/A-quick-tutorial-on-semantic-parsing-with-graphs)

Thanks a lot Alexander.
Sincerely
Victor

**Comment by alexanderkoller** [comment]
Thanks for letting us know - I've fixed the wiki.
