### ISSUE TITLE
Shadow plugin uses log4j / maven repository.

### ISSUE THREAD

**Issue by namednil** [coli-saar/alto#78]
The shadow plugin for compiling alto uses log4j. We should update to version `7.1.1` in `build.gradle` although it's probably not a big issue because it's only used for building the project and not included in alto. I would have done this myself on the spot but in the attempt to find out if alto was the reason why I had a vulnerable version of log4j in my gradle cache, I deleted the cache and now I can't compile and test alto until `http://akci.coli.uni-saarland.de/artifactory/external/` is available again.

I think I encountered that issue with the server in the past. Is there a way to make this run in a more stable manner?

**Comment by alexanderkoller** [comment]
Good catch. As you say, I'm not very worried about the vulnerability in this particular context. Does your analysis mean that other dependencies of Alto don't depend on vulnerable versions of log4j?

Regarding the ability to compile and test, are you using the most recent version of the Alto source? I recently removed the dependency to `akci`, as it doesn't work any more.

**Comment by namednil** [comment]
Good point, yes, I was using an older version. Building alto works for me now.

Yes, my gradle cache doesn't contain an old version of log4j anymore after the update of the shadow plugin.
